// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfoajgxjivtlzteyurhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmb2FqZ3hqaXZ0bHp0ZXl1cmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Nzk0OTAsImV4cCI6MjA1OTA1NTQ5MH0.TO18yYPlRl8X2ZHbBMTvkdluzVsoCsUh-JBC-SoNQ5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);